#!/bin/bash

backlight_file='/sys/class/backlight/intel_backlight/brightness'
newval=$(cat $backlight_file | awk '{print $1 - 50}')
if [ $newval -lt 0 ]; then
	newval='0'
fi
echo $newval > $backlight_file
